<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Contact_slds-icon slds-icon_small</name>
   <tag></tag>
   <elementGuidId>dd9aa5eb-0e12-4190-a0bf-204b4e4d1366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.slds-icon.slds-icon_small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(), &quot;Local Contact&quot;)]/parent::div[@class=&quot;slds-form-element &quot;]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-icon slds-icon_small</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer&quot;)/div[@class=&quot;slds-grid slds-wrap cPricingFieldSetCMP&quot;]/div[@class=&quot;slds-p-around_small slds-col slds-size_12-of-12 slds-small-size_12-of-12 slds-large-size_6-of-12&quot;]/div[@class=&quot;slds-form-element&quot;]/div[@class=&quot;slds-form-element__control&quot;]/div[@class=&quot;slds-combobox_container slds-has-object-switcher&quot;]/div[@class=&quot;slds-listbox_object-switcher slds-dropdown-trigger slds-dropdown-trigger_click&quot;]/button[@class=&quot;slds-button slds-button_icon&quot;]/span[@class=&quot;slds-icon_container slds-icon-standard-account&quot;]/lightning-icon[@class=&quot;slds-icon-standard-account slds-icon_container&quot;]/lightning-primitive-icon[1]/svg[@class=&quot;slds-icon slds-icon_small&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
   </webElementXpaths>
</WebElementEntity>
