<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-primitive-icon_1</name>
   <tag></tag>
   <elementGuidId>8cf21062-7645-4165-af40-180c37285798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;0&quot;] > lightning-primitive-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='components']/div/div[2]/ul/li/div/span/span/button[2]/lightning-primitive-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-primitive-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>396:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;components&quot;)/div[@class=&quot;slds-grid slds-wrap&quot;]/div[@class=&quot;slds-p-around_small slds-size_12-of-12&quot;]/ul[@class=&quot;slds-tree&quot;]/li[@class=&quot;cPricingHierarchieNewCMP&quot;]/div[@class=&quot;slds-tree__item&quot;]/span[@class=&quot;slds-has-flexi-truncate&quot;]/span[@class=&quot;slds-tree__item-label&quot;]/button[@class=&quot;slds-button slds-button_icon slds-m-right_x-small slds-button_icon-bare&quot;]/lightning-primitive-icon[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='components']/div/div[2]/ul/li/div/span/span/button[2]/lightning-primitive-icon</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Min 1 - Max n'])[1]/following::lightning-primitive-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/lightning-primitive-icon</value>
   </webElementXpaths>
</WebElementEntity>
